name: Test

on:
  push:
    branches:
      - develop
  pull_request:

jobs:
  trivy:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    env:
      STATIC_URL: /static/
      STATIC_ROOT:
    steps:
      - name: Install Trivy
        run: |
          curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh -s -- -b /usr/local/bin v0.28.0

      - uses: actions/checkout@v2
      - name: Install dependencies
        run: python -m pip install --upgrade poetry

      - name: Scan
        run: |
          trivy fs  \
          --exit-code 0 \
          src/
